AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  LF1Photos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF1Photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./photos-lambdas/LF1/lambda_function.py
      Description: "Lambda to search photos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::285630149901:role/service-role/codebuild-lambdaBuildProject-service-role"
      Environment:
        Variables:
          REGION: us-east-1
  LF2Photos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF2Photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./photos-lambdas/LF2/lambda_function.py
      Description: "Lambda to index photos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::285630149901:role/service-role/codebuild-lambdaBuildProject-service-role"
      Environment:
        Variables:
          REGION: us-east-1